spring:
  application:
    name: SpringDataJPA
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: test
server:
  servlet:
    context-path: /spring-data-jpa