server:
  port: 9229
spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://database:5432/database
  batch:
    jdbc:
      initialize-schema: never
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:acs/poo/backend/db/migration
