name: Run build & tests

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  pull_request:
    branches: [ "main" ]
    paths:
      - backend/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify --file backend/pom.xml --fail-never

    - name: "Push Docker Image To Registry ( with latest tag )"
      # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PWD }}
        docker build -t feeds-app ./backend
        docker tag feeds-app "${{ secrets.DOCKER_REGISTRY }}/feeds-app:latest"
        docker push "${{ secrets.DOCKER_REGISTRY }}/feeds-app:latest"
